version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kfm2-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-41c36w6dv815"
s3_prefix = "kfm2-app"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

